runtime: custom
env: flex
service: sample-test
network:
  name: projects/republic-network-host/global/networks/dev
  subnetwork_name: republic-subnet-dev
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cpu_utilization:
    target_utilization: 0.50
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 50
